# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/network:
  enable:
    - if: INCLUDE_DEFAULT == 1

examples/network/simple_sniffer:
  disable_test:
    - if: IDF_TARGET not in ["esp32", "esp32c3", "esp32s3"]
      temporary: true
      reason: lack of runners
