# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/get-started/hello_world:
  enable:
    - if: INCLUDE_DEFAULT == 1 or IDF_TARGET in ["esp32h2", "esp32c6"] # preview targets
