# Documentation: .gitlab/ci/README.md#manifest-file-to-control-the-buildtest-apps

examples/ethernet/iperf:
  disable_test:
    - if: IDF_TARGET in ["esp32c3", "esp32c2", "esp32s2", "esp32s3"]
      temporary: true
      reason: lack of runners
